sudo: false
language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - android-22
    - sys-img-armeabi-v7a-android-22
    - add-on
    - extra
licenses:
    - 'android-sdk-license-.+'
jdk:
    - oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-27"

before_script:
  - echo "include ':app', ':commons'" > 'settings.gradle'
  - sed -i.bak '150,163d' $FLAKY_PATH

env:
  - TEST_SUITE=integration_tests
  - TEST_SUITE=unit_tests

script: ./testing $TEST_SUITE

notifications:
  email:
    on_success: never